version: "2.2"

services:
  nextcloud:
    build: ./
    container_name: nextcloud
    #restart: always
    healthcheck:
      test: curl --fail http://127.0.0.1:80/status.php | grep -q -e '"installed":true' -e '"maintenance":false' -e '"needsDbUpgrade":false' || exit 1
      interval: 60s
      timeout: 10s
      #start_period: 5s
      retries: 4
    depends_on:
      nextclouddb:
        condition: service_healthy
      nextcloudredis:
        condition: service_started
    links:
      - nextclouddb
    ports:
      - "80:80"
    volumes:
      - /srv/nextcloud/html:/var/www/html
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      # DB configuration
      - MYSQL_HOST=nextclouddb # same as mysql container name
      - MYSQL_DB=${NEXTCLOUD_DB_NAME}
      - MYSQL_USER=${NEXTCLOUD_DB_USER}
      - MYSQL_PASSWORD=${NEXTCLOUD_DB_PWD}
      # Redis configuration
      - REDIS_HOST=nextcloud_redis
      - REDIS_PORT=6379
      # SMTP configuration
      - SMTP_HOST=nextcloudmailer
      - SMTP_SECURE=
      - SMTP_PORT=1025
      - SMTP_AUTHTYPE=LOGIN
      - SMTP_NAME=${NEXTCLOUD_SMTP_USER}
      - SMTP_PASSWORD=${NEXTCLOUD_SMTP_PWD}
      - MAIL_FROM_ADDRESS=cloud
      - MAIL_DOMAIN=${DOMAIN}
      # Admin configuration
      - NEXTCLOUD_ADMIN_USER=${NEXTCLOUD_ADMIN_LOGIN}
      - NEXTCLOUD_ADMIN_PASSWORD=${NEXTCLOUD_ADMIN_PWD}
      - NEXTCLOUD_TABLE_PREFIX=${NEXTCLOUD_TBL_PREFIX}
      - NEXTCLOUD_TRUSTED_DOMAIN=localhost

  nextclouddb:
    image: mariadb:latest
    container_name: nextclouddb
    restart: always
    command: --character_set_client=utf8 --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --character-set-client-handshake=FALSE
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "--password=${NEXTCLOUD_DB_ROOT_PWD}"]
      timeout: 10s
      retries: 5
    ports:
      - "3306:3306"
    volumes:
      - /srv/nextcloud/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${NEXTCLOUD_DB_ROOT_PWD}
      - MYSQL_DATABASE=${NEXTCLOUD_DB_NAME}
      - MYSQL_USER=${NEXTCLOUD_DB_USER}
      - MYSQL_PASSWORD=${NEXTCLOUD_DB_PWD}

  nextcloudredis:
    image: redis:alpine
    container_name: nextcloudredis
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]

  nextcloudcron:
    build: ./
    container_name: nextcloudcron
    #restart: always
    volumes:
      - /srv/nextcloud/html:/var/www/html
    entrypoint: /cron.sh
    depends_on:
      nextclouddb:
        condition: service_healthy
      nextcloudredis:
        condition: service_started

  nextcloudmailer:
    image: sj26/mailcatcher:latest
    hostname: nextcloudmailer
    container_name: nextcloudmailer
    restart: always
    expose:
      - 1025
    ports:
      - "1080:1080"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
