os: linux
dist: trusty

services: docker

language: shell

branches:
  only:
    - develop
    - master

before_script:
  - env | sort
  - dir="images/${VERSION}/${VARIANT}"

script:
  - cd "$dir"
  - docker-compose build
  - docker images
  - travis_retry docker-compose up -d && sleep 60
  - docker-compose ps
  - docker-compose logs
  - docker-compose ps "nextclouddb" | grep "Up"
  - docker-compose ps "nextcloud" | grep "Up"
  - docker-compose ps "nextcloudcron" | grep "Up"

notifications:
  email: false

env: # Environments
    - VERSION=16.0 VARIANT=fpm-alpine
    - VERSION=16.0 VARIANT=fpm
    - VERSION=16.0 VARIANT=apache
    - VERSION=17.0 VARIANT=fpm-alpine
    - VERSION=17.0 VARIANT=fpm
    - VERSION=17.0 VARIANT=apache
    - VERSION=18.0 VARIANT=fpm-alpine
    - VERSION=18.0 VARIANT=fpm
    - VERSION=18.0 VARIANT=apache
    - VERSION=19.0 VARIANT=fpm-alpine
    - VERSION=19.0 VARIANT=fpm
    - VERSION=19.0 VARIANT=apache
