dist: trusty
sudo: required

services: docker

language: bash

branches:
  only:
    - develop
    - master

before_script:
  - env | sort
  - dir="images/${VERSION}/${VARIANT}"

script:
  - cd "$dir"
  - docker-compose build
  - docker images
  - travis_retry docker-compose up -d && sleep 60
  - docker-compose ps
  - docker-compose logs
  - docker-compose ps "nextclouddb" | grep "Up"
  - docker-compose ps "nextcloud" | grep "Up"
  - docker-compose ps "nextcloudcron" | grep "Up"

notifications:
  email: false

env: # Environments
    - VERSION=14.0 PHP_VERSION=7.2 VARIANT=fpm-alpine
    - VERSION=14.0 PHP_VERSION=7.2 VARIANT=fpm
    - VERSION=14.0 PHP_VERSION=7.2 VARIANT=apache
    - VERSION=15.0 PHP_VERSION=7.2 VARIANT=fpm-alpine
    - VERSION=15.0 PHP_VERSION=7.2 VARIANT=fpm
    - VERSION=15.0 PHP_VERSION=7.2 VARIANT=apache
    - VERSION=16.0 PHP_VERSION=7.2 VARIANT=fpm-alpine
    - VERSION=16.0 PHP_VERSION=7.2 VARIANT=fpm
    - VERSION=16.0 PHP_VERSION=7.2 VARIANT=apache
    - VERSION=17.0 PHP_VERSION=7.2 VARIANT=fpm-alpine
    - VERSION=17.0 PHP_VERSION=7.2 VARIANT=fpm
    - VERSION=17.0 PHP_VERSION=7.2 VARIANT=apache
    - VERSION=18.0 PHP_VERSION=7.2 VARIANT=fpm-alpine
    - VERSION=18.0 PHP_VERSION=7.2 VARIANT=fpm
    - VERSION=18.0 PHP_VERSION=7.2 VARIANT=apache
