version: "2"

services:
  nextcloud:
    build: ./
    container_name: nextcloud
    #restart: always
    depends_on:
      nextclouddb:
        condition: service_healthy
      nextcloudredis:
        condition: service_started
    links:
      - nextclouddb
    ports:
      - 9000:9000
    volumes:
      - /srv/nextcloud/html:/var/www/html
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=nextclouddb # same as pgsql container name
      # https://github.com/nextcloud/docker/issues/456
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nextcloud # same as pgsql POSTGRES_USER env name
      - POSTGRES_PASSWORD=nextcloud # same as pgsql POSTGRES_PASSWORD env name

  nextclouddb:
    image: postgres:latest
    container_name: nextclouddb
    restart: always
    stdin_open: true
    tty: true
    command: postgres -c 'max_connections=500'
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "nextcloud"]
    ports:
      - 5432:5432
    volumes:
      - /srv/nextcloud/db:/var/lib/postgresql/data
    environment:
      # https://github.com/nextcloud/docker/issues/456
      - POSTGRES_DB=workaround
      - POSTGRES_USER=nextcloud
      - POSTGRES_PASSWORD=nextcloud

  nextcloudnginx:
    image: nginx:latest
    container_name: nextcloudnginx
    restart: always
    ports:
      - 80:80
      # If you need SSL connection
      # - '443:443'
    depends_on:
      - nextcloud
    links:
      - nextcloud
    volumes:
      - /srv/nextcloud/html:/var/www/html
      # TODO Provide a custom nginx conf
      #- ./nginx.conf:/etc/nginx/nginx.conf:ro
      # If you need SSL connection, you can provide your own certificates
      # - ./certs:/etc/letsencrypt
      # - ./certs-data:/data/letsencrypt
    environment:
      - NGINX_HOST=localhost # set your local domain or your live domain
      # - NGINX_CGI=nextcloud:9000 # same as nextcloud container name

  nextcloudredis:
    image: redis:alpine
    container_name: nextcloudredis
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]

  nextcloudcron:
    build: ./
    container_name: nextcloudcron
    #restart: always
    volumes:
      - /srv/nextcloud/html:/var/www/html
    entrypoint: /cron.sh
    depends_on:
      nextclouddb:
        condition: service_healthy
      nextcloudredis:
        condition: service_started
