version: "2.2"

services:
  nextcloud:
    build: ./
    container_name: nextcloud
    #restart: always
    healthcheck:
      test: curl --fail http://127.0.0.1:80/status.php | grep -q -e '"installed":true' -e '"maintenance":false' -e '"needsDbUpgrade":false' || exit 1
      interval: 60s
      timeout: 10s
      #start_period: 5s
      retries: 4
    depends_on:
      nextclouddb:
        condition: service_healthy
      nextcloudredis:
        condition: service_started
    links:
      - nextclouddb
    ports:
      - 80:80
    volumes:
      - /srv/nextcloud/html:/var/www/html
    environment:
      - REDIS_HOST=redis
      - MYSQL_HOST=nextclouddb # same as mysql container name
      - MYSQL_DB=nextcloud # same as mysql MYSQL_DATABASE env name
      - MYSQL_USER=nextcloud # same as mysql MYSQL_USER env name
      - MYSQL_PASSWORD=nextclouddbpass # same as mysql MYSQL_PASSWORD env name

  nextclouddb:
    image: mariadb:latest
    container_name: nextclouddb
    restart: always
    command: --character_set_client=utf8 --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --character-set-client-handshake=FALSE
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 5
    ports:
      - 3306:3306
    volumes:
      - /srv/nextcloud/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=mysqlrootpassword
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=nextclouddbpass

  nextcloudredis:
    image: redis:alpine
    container_name: nextcloudredis
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]

  nextcloudcron:
    build: ./
    container_name: nextcloudcron
    #restart: always
    volumes:
      - /srv/nextcloud/html:/var/www/html
    entrypoint: /cron.sh
    depends_on:
      nextclouddb:
        condition: service_healthy
      nextcloudredis:
        condition: service_started
