#!/bin/bash

# See documentation for details:
# https://docs.docker.com/docker-hub/builds/advanced/

#echo 'Set permissions for persisted data...'
#mkdir -p '/srv/nextcloud/html'
#chown "1000:1000" '/srv/nextcloud/html'
#chmod 777 '/srv/nextcloud/html'
