
name: Docker Image CI

on:
  pull_request:
  push:
    branches:
      - master
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ['18.0', '19.0', '20.0', '21.0']
        variant: ['apache', 'fpm', 'fpm-alpine']

    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Execute CI hooks
        id: docker_hooks
        run: |
          cd images/${{ matrix.version }}/${{ matrix.variant }}
          ./hooks/run

      - name: Display docker images
        run: docker images
